name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: checkout stage
      uses: actions/checkout@v1
      with:
        ref: ci-stage-server
    - name: merge
      env:
        GITHUB_SHA: ${{ github.sha }}
      run: git merge $GITHUB_SHA -m "Merge branch 'master' into 'ci-stage-server'"
    - name: push
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ci-stage-server
    - name: The job has failed
      if: failure()
      uses: drilonrecica/action-slack-notify@0.0.3
      env:
        SLACK_COLOR: '#D00000'
        SLACK_ICON: https://github.com/guitarama.png?size=48
        SLACK_MESSAGE: 'Failed to merge `master` to `ci-stage-server` :boom:'
        SLACK_TITLE: Merge Failure!
        SLACK_USERNAME: github
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
