name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: checkout stage
      uses: actions/checkout@v1
      with:
        ref: ci-stage-server
    - name: merge
      env:
        GITHUB_SHA: ${{ github.sha }}
      run: git merge $GITHUB_SHA -m "Merge branch 'master' into ci-stage-server"
    - name: push
      run: git push
